"""Public ARES SDK import surface.

Prefer this package for module authoring and local integrations:

    from ares.sdk import BaseModule, ExecutionContext, ModuleResult

The legacy ``ares.modules.sdk`` path remains available for existing modules.
"""
from __future__ import annotations

from ares.modules.sdk import (
    AccountLocked,
    AresError,
    ArtifactStore,
    AuthenticationFailed,
    BaseModule,
    ConnectionRefused,
    ConnectionTimeout,
    CredentialArtifact,
    CredentialError,
    CredentialExpired,
    DetectionSignal,
    ExecutionContext,
    ExecutionError,
    Finding,
    HashArtifact,
    HoneypotDetected,
    HostArtifact,
    HostUnreachable,
    InsufficientPrivilege,
    InvalidContext,
    ModuleError,
    ModuleResult,
    ModuleTestHelper,
    ModuleTimeoutError,
    ModuleValidationError,
    NetworkError,
    NoCredentialsAvailable,
    OpsecError,
    OpsecLevel,
    PermissionArtifact,
    SandboxError,
    ScopeError,
    Severity,
    TechniqueLibrary,
    TechniqueMapper,
    UserArtifact,
    get_logger,
    module_metadata,
    requires_privilege,
    timeout,
    validate_module_class,
)

__all__ = [
    "BaseModule",
    "ModuleResult",
    "OpsecLevel",
    "validate_module_class",
    "ExecutionContext",
    "AresError",
    "ModuleError",
    "ModuleValidationError",
    "ModuleTimeoutError",
    "NetworkError",
    "ConnectionRefused",
    "ConnectionTimeout",
    "HostUnreachable",
    "CredentialError",
    "AuthenticationFailed",
    "AccountLocked",
    "CredentialExpired",
    "NoCredentialsAvailable",
    "ExecutionError",
    "SandboxError",
    "ScopeError",
    "OpsecError",
    "DetectionSignal",
    "HoneypotDetected",
    "InsufficientPrivilege",
    "InvalidContext",
    "Finding",
    "Severity",
    "get_logger",
    "TechniqueLibrary",
    "TechniqueMapper",
    "ArtifactStore",
    "HostArtifact",
    "UserArtifact",
    "CredentialArtifact",
    "HashArtifact",
    "PermissionArtifact",
    "module_metadata",
    "requires_privilege",
    "timeout",
    "ModuleTestHelper",
]
